= ES6/7-CHEAT-SHEET
Jean-François Le Foll (@JeffLeFoll)
:source-highlighter: pygments
:nofooter:

:nbColonnes: 1

[grid=none]
[frame=none]
[width=95%]
[cols="{nbColonnes}*.^"]
|===

a| *Assignation de variable*
[source, javascript]
----
> const pi = 3.14;
> pi = 3.15
x TypeError: invalid assignment to const pi

> let foo = 'bar';
> console.log(foo)
< "bar"
> foo = 'foo'
> console.log(foo)
< "foo"
> let foo = 'toto'
x SyntaxError: redeclaration of let foo
----

a| *Fonction fléchée* (https://repl.it/@JeffLeFoll/FonctionFlechee)
[source, javascript]
----
> let addition = (x, y) => x + y; 
> addition(4,5);
< 9

Equivaut à : 

> let addition = (x, y) => {
    return x + y;
}; 

> let addition = function(x,y) {
    return x + y;
}
----

a| *Gestion des paramètres* (https://repl.it/@JeffLeFoll/Parametres)
[source, javascript]
----
> let additionAvecMinimum1 = (x, y=1) => x + y; 
> additionAvecMinimum1(4);
< 5

> let addition = (...valeurs) => valeurs.reduce((total, valeur) => total + valeur ); 
> addition(5,6,7);
< 18

> let soustraction = (x, ...[a, b, c]) => x + a - b - c;
> soustraction(1, 20, 5, 2, 45);
< 14
----

a| *Manipulation des tableaux* (https://repl.it/@JeffLeFoll/Array)
[source, javascript]
----
> ['foo', 'bar', 'flop'].filter(item => item.startsWith('f')); 
< [ "foo", "flop" ]

> [1, 2, 3].reduce((total, valeur) => total + valeur);
< 6

> ['toto', 'pop', 'start'].map(item => item.split('').reverse().join(''));
> [ "otot", "pop", "trats" ]

> ['foo', 'polf', 'flop'].map(item => item.split('').reverse().join(''))
.filter(item => item.startsWith('f'));
< ['flop']
----

a| *Classe* (https://repl.it/@JeffLeFoll/ES6class)
[source, javascript]
----
> class Vehicule {
    constructor(couleur, puissance) {
        this._couleur = couleur;
        this._puissance = puissance;
    }

    get puissance() {return this._puissance}

    get couleur() {return this._couleur}

    set couleur(nouvelleCouleur) {this._couleur = nouvelleCouleur}
}

> let unVehicule = new Vehicule('rouge', '7cv');
> console.log(unVehicule.couleur);
< 'rouge'
> unVehicule.couleur = 'vert';
> console.log(unVehicule.couleur);
< 'vert'
> console.log(unVehicule.puissance);
< '7cv'
> unVehicule.puissance = '4cv';
> console.log(unVehicule.puissance);
< '7cv'
----

a| *Classe - Extension* (https://repl.it/@JeffLeFoll/ES6ClassExt)
[source, javascript]
----
> class Moto extends Vehicule {
    constructor(couleur, puissance, type) {
        super(couleur, puissance);
        this._type = type;
    }

    debridage(nouvellePuissance) {this._puissance = nouvellePuissance}

    static warning() {return 'N\'oubliez pas les équipements de sécurités'}
}

> let gsr600 = new Moto('gris', '98cv', 'roadster');
> console.log(gsr600.couleur);
< 'gris'
> console.log(gsr600.puissance);
< '98cv'
> gsr600.debridage('110cv');
> console.log(gsr600.puissance);
< '110cv'
> Moto.warning();
< "N'oubliez pas les équipements de sécurités"
----
|===
<<<
[grid=none]
[frame=none]
[width=95%]
[cols="{nbColonnes}*.^"]
|===


a| *Scoped Function* (https://repl.it/@JeffLeFoll/ScopedFunction)
[source, javascript]
----
> (function() {
  let texte = 'Je suis une fonction auto-appelante !';
  console.log(texte);
})();
< Je suis une fonction auto-appelante !

Devient : 

> {
  let texte = 'Moi pareil mais avec une syntaxe plus simple ! :)';
  console.log(texte);
}
< Moi pareil mais avec une syntaxe plus simple ! :)
----

a| *Template Literals* (https://repl.it/@JeffLeFoll/TemplateLiterals)
[source, javascript]
----
> let personne = {prenom:'James', nom:'Bond'};
> let exclam = 'AH AH !';

> console.log(`My name is ${persone.nom}, 
            ${personne.prenom} 
      ${personne.nom}
-- ${exclam} --`);

< My name is Bond, 
            James 
      Bond
-- Ah Ah ! --
----


a| *Destructuration* (https://repl.it/@JeffLeFoll/Destructuration)
[source, javascript]
----
> let tableauSource = [1, 2, 3, 4];
> let dest1, dest2, reste;

> [dest1, dest2, ...reste] = tableauSource;
> console.log(dest1); // 1
> console.log(dest2); // 2
> console.log(reste); // [3, 4]

> let personne = {nom: 'Bond', prenom: 'James'};
> let {nom, prenom} = personne;
> console.log(nom); // Bond
> console.log(prenom); // James

> let url = 'https://developer.mozilla.org/en-US/Web/JavaScript';
> let parsedURL = /^(\w+)\:\/\/([^\/]+)\/(.*)$/.exec(url);
> console.log(parsedURL);
< ['https://developer.mozilla.org/en-US/Web/JavaScript', 'https', 
< 'developer.mozilla.org','en-US/Web/JavaScript']

> let [source, protocol, fullhost, fullpath] = parsedURL;
> console.log(protocol); // https
----

a| *Promesses* (https://repl.it/@JeffLeFoll/Promesse)
[source, javascript]
----
> let promesse = new Promise((resolve, reject) => {
  setTimeout(() => resolve('Success!'), 250);
});

> promesse.then(message => console.log(message));
< Success!

> promesse
  .then(message => message + ' bingo')
  .then(messageModifie => console.log(messageModifie))
  .catch(reason => console.log('Error : ' + reason));
< Success! bingo
----

a| *Fetch API* (https://repl.it/@JeffLeFoll/HttpRequest)
[source, javascript]
----
> fetch('https://swapi.co/api/starships/10/')
  .then(reponse => {
    if (reponse.ok) {
      return reponse.json();
    }
    throw new Error('Network response was not ok.');
  })
  .then(data => console.log('fetch: ' + data.name))
  .catch(error => console.log('Problem : ' + error));
< fetch: Millennium Falcon

> let options = {
  method: 'GET',
  headers: new Headers(),
  mode: 'cors',
  cache: 'default',
};
> fetch('https://swapi.co/api/starships/10/', options);
----

a| *HttpRequest* (https://repl.it/@JeffLeFoll/HttpRequest)
[source, javascript]
----
> let xhr = new XMLHttpRequest();
> xhr.open('get', 'https://swapi.co/api/starships/10/', true);
> xhr.responseType = 'json';
> xhr.onload = function() {
  let status = xhr.status;
  if (status == 200) {
    console.log('xhr: ' + xhr.response.name);
  } else {
    console.log('Network response was not ok.');
  }
};
> xhr.send();
< xhr: Millennium Falcon
----

|===
<<<
[grid=none]
[frame=none]
[width=95%]
[cols="{nbColonnes}*.^"]
|===


a| *Async / Await* (https://repl.it/@JeffLeFoll/AsyncAwait)
[source, javascript]
----
 > async function loadData(url) {
    let response = await fetch(url);
    let data = await response.json();
    return data;
  }

 > let data = await loadData('https://swapi.co/api/starships/10/');
 > console.log(data.name);
 < Millennium Falcon
----

a| *JavaScript Module* (http://jeff.lefoll.info/es6-cheat-sheet/exemples/imports/index.html)
[source, javascript]
----
 -- A tester avec Chrome ou Firefox (activer le flag :
 -- dom.moduleScripts.enabled dans la page about:config )
 -- Logger.js
 export class Logger {
  static log(logMessage) {
    console.log('From Logger : ' + logMessage);
  }
}
-- Main.js
import { Logger } from './Logger.js';

export class Main {
  constructor(message) {
    Logger.log(message);
  }
}
-- index.html
    <script type="module">
        import { Main } from './Main.js';
        let main = new main('Bingo !!');    
    </script>

< From Logger : Bingo !!
----

a| *Prototype* (https://repl.it/@JeffLeFoll/Prototype)
[source, javascript]
----
> function Moto(couleur) {this.couleur = couleur;} 

> let motoRouge = new Moto('rouge'); 
> console.log(motoRouge.type); // undefined

> Moto.prototype.type = 'sportive';

> let motoBleu = new Moto('bleu');
> motoBleu.type = 'roadster';

> console.log(motoRouge.type); // "sportive"
> console.log(motoBleu.type); // "roadster"

> motoBleu.carburan = 'essence';
> console.log(motoRouge.carburan); // "undefined"
> console.log(motoBleu.carburan); // "essence"

> Moto.prototype.avancer = function (distance) {}
----

a| *JSON to ES Class* (https://repl.it/@JeffLeFoll/JSON2Class)
[source, javascript]
----
> let jsonData = { nom: 'Bond', prenom: 'James' };

> jsonData.presentation = () => jsonData.nom + ', ' + jsonData.prenom;
> console.log(jsonData.presentation());
< Bond, James

> let autreJsonData = { nom: 'Trevelyan', prenom: 'Alec' };
> console.log(autreJsonData.presentation()); 
< TypeError: autreJsonData.presentation is not a function

> class Personne {
  constructor({ nom, prenom }) {
    this.nom = nom;
    this.prenom = prenom;
  }

  presentation() {
    return this.nom + ', ' + this.prenom;
  }
}

> let agent006 = new Personne(autreJsonData);
> console.log(agent006.presentation());
< Trevelyan, Alec
----

a| *Collections* (https://repl.it/@JeffLeFoll/Collections)
[source, javascript]
----
> let tableau = ['foo', 'bar', 'toto'];
> tableau.push('bar'); 
< ['foo', 'bar', 'toto', 'bar']

> let liste = new Set();
> liste.add('foo').add('bar').add('toto').add('bar'); 
< Set { 'foo', 'bar', 'toto' }

> liste.has('bar');
< true

> liste.forEach(value => {});
> [...liste].filter(item => {});

> let map = new Map();
> map.set(1, 'Toto');
> map.set(2, 'Toto');
> map.set(1, 'Foo');
< Map { 1 => 'Foo', 2 => 'Toto' }

> for (let [cle, valeur] of map.entries()) {}
> map.forEach((valeur, cle) => {})
----

a| *Test unitaire* (http://jeff.lefoll.info/es6-cheat-sheet/exemples/tests/mocha.html)
[source, javascript]
----
-- Agent.js
class Agent {
  constructor(nom, prenom, code) {
    this.nom = nom;
    this.prenom = prenom;
    this._code = code;
  }
  presentation() { 
    return this.nom + ', ' + this.prenom; 
  }
  getCode() { 
    return this._code; 
  }
}
-- AgentSpec.js
chai.should(); // ou let expect = chai.expect;
describe("Le comportement d'un Agent est", () => {
  let monAgent;
  beforeEach(() => {
    monAgent = new Agent('Bond', 'James', '007');
  });
  it('doit se presenter', () => {
    monAgent.presentation().should.equal('Bond, James');
  });
});
----

|===
<<<
[grid=none]
[frame=none]
[width=95%]
[cols="{nbColonnes}*.^"]
|===


a| *Coercition* (https://repl.it/@JeffLeFoll/Coercition)
[source, javascript]
----
console.log(5 + 2);       // 
console.log(5 + null);    //
console.log('5' + 2);     //
console.log('5' + null);  //
console.log('5' - 2);     //
console.log('5' * '2');   //
console.log('55' == 55);  //
console.log('55' === 55); //
----

a|
----
----

a| *Dans le doute*
----
    https://developer.mozilla.org
    https://caniuse.com/
    https://github.com/airbnb/javascript
----

|===

